src/Classes/API/Headers.php
src/Classes/APIService.php
src/Classes/ImmutableObject.php
src/Classes/IterableArray.php
src/Classes/ParameterBag.php
src/Classes/StandardOutput.php
src/Database/Model.php
src/Database/Relations/HasManyFromAPI.php
src/Exceptions/InvalidArgumentException.php
src/Interfaces/Photo.php
src/Interfaces/Vehicle.php
src/Traits/ConsoleOutputter.php

A class to easily parse headers from a guzzle response
Added toArray to ImmutableObject
Created an IterableArray, which is a way to easily provide basic arrays when something type hints Iterable.
Created ParameterBag, an easy way to interact with parameters passed to services. It's like Illuminate's Request object, but lighter and specific to our needs.
Modified standard output: changed errors to be red background white text, instead of red text, automatically pad lines to try to make them even width.
Modified ConsoleOutputter trait to accept all output optionally as you would provide for sprintf, so you can now do: `$this->info('Updated %', $vehicle->vin)`. Also added an onBind event you can assign a closure to, when bind is called, this closure will fire. I used this mechanic to assign …

improved and added new features

---

.gitignore
composer.json
src/Classes/API/CachesRequests.php
src/Classes/ImmutableObject.php
src/FrontEnd/ScriptCache.php
src/Interfaces/Filtering/CustomerAssociation.php
src/Interfaces/MarketingSuite/Campaign.php
src/Testing/Application.php
src/Testing/TestSqliteDatabase.php
src/Traits/AttributeArrayAccess.php
tests/Unit/Classes/API/MultipartPayloadTest.php
tests/Unit/Classes/APIServiceTest.php
tests/Unit/Classes/GenericUtilityTest.php
tests/Unit/Classes/ImmutableModelTest.php
tests/Unit/Classes/ImmutableObjectTest.php
tests/Unit/Classes/StandardOutputTest.php
tests/Unit/Database/APIAssociatesTest.php
tests/Unit/Database/ApiModelTest.php
tests/Unit/Database/ComplexQueryParserTest.php
tests/Unit/Database/HasManyFromAPITest.php
tests/Unit/Exceptions/InvalidPayloadExceptionTest.php
tests/Unit/Testing/SmartAssertionsTest.php
tests/Unit/Testing/TestCaseTest.php

lets you access immutable objects like arrays
$response->content
$response['content']
Fixes up the tests for phpunit 8
Fixes linting errors

Bump 4408: ImmutableObject array access

---

src/Interfaces/MarketingSuite/Campaign.php

I needed this for retention as a way to say, when the send_email toggle is on, look at the email_at value etc. I don't know if this provides value in conquest, it may not, but the timing service uses this contract so I added it here.
https://vicimus.atlassian.net/browse/BUMP-5826

feat(shared): campaign provides its medium associations

---

src/Database/Model.php

This change is required to retain how dates were handled in Laravel 6.
https://vicimus.atlassian.net/browse/BUMP-5946

required for new carbon stuff

---

src/Interfaces/MarketingSuite/Assets/PlaceholderData.php

Allows store to be nullable on the placeholder data service. This is necessary when generating previews and we have no store.
https://vicimus.atlassian.net/browse/BUMP-6400

feat(shared): placeholder data store optional

---

src/Interfaces/MarketingSuite/Audience.php
src/Interfaces/MarketingSuite/PurlContract.php

When uploading a custom audience to Facebook the complex criteria is not necessary. It's just an array of custom audience ids on Facebook.
https://vicimus.atlassian.net/browse/BUMP-6399

fix(conquest): audience does not have to provide criteria

---

src/Interfaces/MarketingSuite/Campaign.php

This is replaced by the Launchable interface, which is only implemented by the Conquest campaign type ( and InventoryCampaignVehicle) and allows the identifier() method to be removed from other campaign types which it made no sense for. 
This change frees up the identifier method, used by Identifiable interface which InventoryCampaignVehicle also implements. 
https://vicimus.atlassian.net/browse/BUMP-7180

dev(shared): remove identifier from campaign contract

---

src/Interfaces/MarketingSuite/Audience.php
src/Interfaces/MarketingSuite/Campaign.php
src/Interfaces/MarketingSuite/ConquestDataSource.php
src/Interfaces/MarketingSuite/HasSource.php

Audience::target() accepts the asset type, this allows the specific placements to be added for the target.
Categories removed from campaign contract, this has been moved to the HasSource interface as it makes no sense for retention to implement this.
DataSource has two be methods: 
create, so campaigns can be created separately from 'other things' like publishing assets which take time, but allows the creation request to fail in real time.
mediumsUpdated, so that if an asset is enabled/disabled post launch the ad sets can be synchronized appropriately. This is no longer used after the change to only send to the source after launching - since assets aren't editable after the fact - but they could be and will be in inventory ads.
https://vicimus.atlassian.net/browse/BUMP-7367

dev(shared): data sources create

---

src/Interfaces/MarketingSuite/Assets/AdSet.php
src/Interfaces/MarketingSuite/Assets/Creatable.php
src/Interfaces/MarketingSuite/SourceRecord.php

Ad sets are now stored. Sources have many ad sets. Createables belong to an ad set.
https://vicimus.atlassian.net/browse/BUMP-7779

dev(inventory-ads): ad set changes

---

src/Interfaces/MarketingSuite/HasSource.php

Turns out this was required for the mailable.
https://vicimus.atlassian.net/browse/BUMP-7819

dev(shared): has source gets paused message

---

src/Interfaces/MarketingSuite/Audience.php

Adds a method to parse a remote id from an audience. This is necessary so that if a saved facebook audience is selected for a campaign, the audience can be found and displayed to the user.
https://vicimus.atlassian.net/browse/BUMP-8097

dev(shared): audience remoteId

---

src/Interfaces/MarketingSuite/Audience.php
src/Interfaces/MarketingSuite/ConquestDataSource.php
src/Interfaces/MarketingSuite/HasSource.php

Changes typehint on audiences target method, it was passing the 'creatable' to get an asset type slug off of it. Im working with ad sets now more often, so now just pass the placement type directly.
https://vicimus.atlassian.net/browse/BUMP-8142

dev(inventory-ads): audience targeting tweaks

---

src/Interfaces/MarketingSuite/ConquestDataSource.php

Adds a save method to the source contract so that if a source needs to do somethign special on it's creation (generate assets/identifiers) it is handled at the source level.
https://vicimus.atlassian.net/browse/BUMP-8212

dev(shared): source has save 

---

composer.json
src/Classes/ConquestDataSourceInfo.php
tests/Unit/Classes/ConquestDataSourceInfoTest.php

Datasource is aware of the campaigns which it supports. This allows purl only campaigns to be only offered on conquest campaigns.
https://vicimus.atlassian.net/browse/BUMP-8274

dev(shared): data source provides supported

---

src/Interfaces/MarketingSuite/PurlContract.php

Purl manager instance is capable of finding a background for a provided campaign id.
https://vicimus.atlassian.net/browse/BUMP-8256

dev(shared): purl manager has background

---

src/Interfaces/MarketingSuite/Assets/Placeholders.php

Now that it's public it needs to be on the interface.
https://vicimus.atlassian.net/browse/BUMP-8336

dev(shared): editor if

---

src/Interfaces/MarketingSuite/ConquestDataSource.php

Sometimes, before a datasource processes some preliminary setup needs to happen (mega carousel). That can happen in here.
https://vicimus.atlassian.net/browse/BUMP-8337

dev(shared): datasource has setup

---

composer.json
src/Interfaces/Filtering/Campaign.php
src/Interfaces/Filtering/Gatherer.php
src/Interfaces/Filtering/ResultConfiguration.php
src/Interfaces/Filtering/Stats.php
src/Interfaces/OemService.php

I rewrote our Gatherer from scratch. This is the service that converts a filter into a set of customers (as well as generates stats). Typical filter usage is the default settings plus bucket, and restrict vehicles. With those values, my new gatherer (Super Gatherer) reduces CPU usage by 94% and is around 87% faster, and also reduces the amount of time MySQL is computing by 84% which will lighten the load on our rds server as well as our web server.
In addition to this, I've added multiple new filter controls, as these all required handlers for the new gatherer, so I figured it's the best time to implement them.
https://vicimus.atlassian.net/browse/BUMP-6440
https://vicimus.atlassian.net/browse/BUMP-8652
https://vicimus.atlassian.net/browse/BUMP-8252 …

dev(retention): rewrote gatherer and added many filter controls

---

src/Database/Model.php

We used to have this for reasons, but it's messing up Safari, and I'd rather rely on default Laravel functionality and fix any issues we caused ourselves.
https://vicimus.atlassian.net/browse/BUMP-9023
https://vicimus.atlassian.net/browse/BUMP-9026

fix(shared): fix date serialization to use Laravels default

---

src/Interfaces/Filtering/Stats.php
src/Interfaces/MarketingSuite/PurlEvents.php

Adf info is manually handled in the submission logic after the appropriate store is determined for whitelabelling purposes.
https://vicimus.atlassian.net/browse/BUMP-9519

dev(shared): purl event no longer takes adf info

---

bootstrap/dev-helpers.php
bootstrap/helpers.php

It exists in two places, so i just kept them the same.
1. If the app's locale is english, we don't have to translate anything. If a default is provided, then that is just the english word, we can just turn around and return the english word and save all the look ups. This eliminates 99% of all overhead for translating.
2. If it can't do the above, it will cache the results now so it only has to do the lookup once.
https://vicimus.atlassian.net/browse/GBX-5936
https://vicimus.atlassian.net/browse/GBX-5933
https://vicimus.atlassian.net/browse/GBX-5932

dev(shared): make the tran() method way more effecient

---

bootstrap/helpers.php

The hash being created for the cache was overwriting the key being passed which is required for the tran() to work properly and find the translation.
https://vicimus.atlassian.net/browse/GBX-5941

fix(shared): keep the key for the tran function and use $hash variable instead

---

src/Interfaces/MarketingSuite/Campaign.php

Bool if casting is on, but we can turn it off, so then they are ints, so these updated annotations are more accurate and will let phpstorm highlight possible issues and where manual casting may be preferred.
https://vicimus.atlassian.net/browse/BUMP-10445

dev(shared): improve some annotations

---

src/Interfaces/Glovebox/Result.php

This interface was incorrect. It also has no business being in a Glovebox namespace but it was too much work to move it at this time. Executor/Result is used in tons of projects all over, nothing to do with Gbx.
https://vicimus.atlassian.net/browse/GBX-6127

dev(shared): fix interface

---

src/Interfaces/Glovebox/ThemeManager.php

Needed to add the $command parameter to the ThemeManager interface for gbx.
https://vicimus.atlassian.net/browse/GBX-6206

fix(gbx): add command param to theme manager

---

src/Interfaces/Filtering/Campaign.php

Added for lifecycle campaigns when logic needs to know something from the campaigns filter, but lifecycle does not have a filter and stores these answers differently.
https://vicimus.atlassian.net/browse/BUMP-10840

dev(retention): campaign/filter questions

---

src/Classes/ImmutableObject.php

We originally had it annotated as stdClass but in fact it can and should alllow any object type (or array). This fixes an issue where OEM was passing it an alreadyt built ImmutableObject and it crashed saying it had to be an array or stdClass.
https://vicimus.atlassian.net/browse/BUMP-11986

dev(shared): allow any object in ImmutableObject constructor

---

src/Interfaces/Store.php

Model.php and Store.php both had a setAttribute method but the return was different. Model one overrides Laravel, so that's the signature I went with and this should fix issues when upgrading packages that use these classes.
https://vicimus.atlassian.net/browse/BUMP-12102

dev(shared): fix a flaw in the interface

---

src/Interfaces/Leads/Distribution.php
src/Interfaces/Leads/HttpCallbackHandler.php

When sending http leads, the distribution needs to be able to say what store id it is for.
https://vicimus.atlassian.net/browse/BUMP-12369

dev(shared): support for http callbacks

---

src/Interfaces/MarketingSuite/Assets/Creatable.php
src/Interfaces/MarketingSuite/Campaign.php
src/Interfaces/MarketingSuite/SimpleProperties.php

The hidden field is stored as a 0 or 1, the true/false property here was causing unnecessary audits.
https://vicimus.atlassian.net/browse/BUMP-12501

dev(shared): record interface change

---

src/Locale/Compiler.php
src/Locale/Translation.php

Caching can happen outside of this class, so removed the two dependencies that were required just for caching. Made it able to scan and include sub-files within the directory automatically, so we no longer need to explicitly include them. Added support for the complex translation types that contain context and file locations.
https://vicimus.atlassian.net/browse/BUMP-12309

dev(shared): improve the compiler to be awesome

---

src/Interfaces/MarketingSuite/HasSource.php
src/Interfaces/MarketingSuite/SourceRecord.php

Adds a method to retrieve the associated campaign from a source record.
https://vicimus.atlassian.net/browse/BUMP-12874

dev(shared): source record has campaign

---

src/Classes/DateTime.php

We should be using Carbon, not this.
https://vicimus.atlassian.net/browse/BUMP-13091

dev(shared): deprecate custom datetime class
