Vicimus/Support

src/Exceptions/RestException.php
can now do in a catch:
```
return response()->json($ex, $ex->getCode());
```
=> added json serialization

src/Classes/API/Headers.php, src/Classes/API/MultipartPayload.php, src/Classes/APIService.php, src/Classes/ImmutableObject.php, src/Classes/Tools.php, src/Database/APIAssociates.php, src/Database/ComplexQueryParser.php, src/Database/Relations/HasManyFromAPI.php, src/Exceptions/UtilityException.php, src/Services/Authentication.php, tests/Unit/Classes/API/HeadersTest.php, tests/Unit/Classes/API/MultipartPayloadTest.php, tests/Unit/Classes/ImmutableObjectTest.php, tests/Unit/Classes/LumenRouterTest.php, tests/Unit/Database/APIAssociatesTest.php, tests/Unit/Database/HasManyFromAPITest.php
Adds tests to get more code coverage on one of our most used packages.
=> code coverage

src/Classes/BasicVideo.php, src/Interfaces/Video.php
For https://vicimus.atlassian.net/browse/GYT-5
=> Create Video interface and BasicVideo class

src/Database/Model.php
Both phpcs and phpunit are failing but all I added was an `@method` so it can go screw itself
=> more property hints

scripts/2pac.sh, scripts/install.sh
Fixes https://vicimus.atlassian.net/browse/BUMP-1335
=> Add 2pac scripts, make 2pac detect untracked files, create install script to create alias

composer.json, src/helpers.php
Fixes https://vicimus.atlassian.net/browse/BUMP-2174
=> Create helpers.php file for helper functions

resources/views/emails/partials/base.blade.php, resources/views/emails/partials/button.blade.php, src/Classes/Tools.php
Centralize the email template so we can use it everywhere.
Add a new date parsing method so that we can parse dates one row at a time so we dont have to store a million rows in memory to do it.
=> improvements

src/Http/Request.php
Allows for constructor to accept array of parameters which is then converted to the request object.
Allows a third parameter of the cast property to be passed to the get method to cast in the event of the property existing in the request object.
=> BUMP-2503 Constructor changes and cast

src/Exceptions/CalculatorException.php, src/Services/LeaseCalculator.php
https://vicimus.atlassian.net/browse/GYT-353
=> Add an exception for lease payment period being zero

src/Interfaces/MarketingSuite/Campaign.php
https://vicimus.atlassian.net/browse/BUMP-4146
=> Added some new properties here

src/Interfaces/Filtering/Campaign.php
=> add notes to campaign

src/Interfaces/MarketingSuite/Campaign.php
=> SP-371 Campaign has acknowledgements

src/Classes/RenderSpecs.php, src/Testing/TestSqliteDatabase.php
These changes are required for customer-api tests to work.
=> feat(database): introduce database aliases

src/Interfaces/Filtering/Stats.php
Added the $rvms property to the Stats interface to use when building a new stats model
https://vicimus.atlassian.net/browse/BUMP-5313
=> fix(retention): add property $rvms to Stats interface

src/Interfaces/MarketingSuite/Assets/Placeholders.php
Placeholders isValidPlaceholder interface accepts a campaign type which determines the valid placeholders
https://vicimus.atlassian.net/browse/BUMP-5724
=> feat(interface): placeholder interface change

src/Interfaces/MarketingSuite/Audience.php
Adds a flag which allows us to indicate to the audience that we want the data in the pure form in which it's stored or impure so that it's manipulated in a manor that the data source requires.
https://github.com/Vicimus/Support/compare/BUMP-5862
=> feat(conquest): pure flag to audience

src/Interfaces/MarketingSuite/Campaign.php
A campaign provides a way to get it's associated campaign id
https://vicimus.atlassian.net/browse/BUMP-5869
=> feat(interface): campaign gets form id

src/Testing/BasicCache.php
This snuck its way into the code.
=> Remove php7 feature from php5 branch

src/Interfaces/MarketingSuite/Audience.php, src/Interfaces/MarketingSuite/ConquestDataSource.php, src/Interfaces/MarketingSuite/Exceptions/UpdateException.php
Datasource has an update method
https://vicimus.atlassian.net/browse/BUMP-6066
=> feat(conquest): sources update

src/Classes/Grouping.php
All asset groups will use this method by default.
https://vicimus.atlassian.net/browse/GOOG-15
=> feat(properties): moves parse logic

src/Interfaces/MarketingSuite/CriteriaContract.php
Google targeting consists of criteria added to the campaign and other criteria added to the ad group.
https://vicimus.atlassian.net/browse/GOOG-17
=> feat(conquest): criteria provides a group payload

src/Interfaces/MarketingSuite/ConquestDataSource.php, src/Interfaces/MarketingSuite/SourceRecord.php
Data sources implement the reschedule method
https://vicimus.atlassian.net/browse/GOOG-33
=> feat(conquest): source reschedules

src/Interfaces/MarketingSuite/CriteriaContract.php
Group payload was too vague. A group can have biddable, negative or positive criteria. Though i'm yet to run into positive on a group.
https://vicimus.atlassian.net/browse/GOOG-38
=> criteria contract changes

src/Interfaces/Filtering/CustomerAssociation.php, src/Interfaces/MarketingSuite/ConquestDataSource.php
Plus a random customer fix I'll throw in for free.
https://vicimus.atlassian.net/browse/BUMP-6214
=> feat(conquest): changes for datasources

src/Interfaces/MarketingSuite/ReportData.php
Interface for the data returned from a source report
=> report data interface

src/Interfaces/MarketingSuite/ConquestDataSource.php
Additional method for data sources.
https://vicimus.atlassian.net/browse/BUMP-6196
=> feat(conquest): destroy method for conquest

src/Interfaces/MarketingSuite/Asset.php
Check assets approved/active states.
https://vicimus.atlassian.net/browse/BUMP-6178
=> feat(asset): asset has active/approved

src/Interfaces/MarketingSuite/ConquestDataSource.php
Sources report approved
https://vicimus.atlassian.net/browse/GOOG-27
=> feat(interface): source approved

src/Interfaces/MarketingSuite/Campaign.php
Campaign interface provides a copy relationship
https://vicimus.atlassian.net/browse/BUMP-6318
=> feat(shared): campaign provides copy

src/Classes/ComplexValue.php, src/Classes/Properties/Finder.php, src/Classes/Properties/Values.php, src/Interfaces/MarketingSuite/Assets/PropertyProvider.php, tests/Unit/Classes/ComplexValueTest.php
Provide a store id to property related methods which allows the property provider to make http calls to populate the options on behalf of the store.
https://vicimus.atlassian.net/browse/BUMP-6403
=> feat(shared): property methods use store

src/Interfaces/MarketingSuite/Campaign.php
Campaigns can provide their categories
https://vicimus.atlassian.net/browse/BUMP-6531
=> feat(shared): campaigns have categories

src/Interfaces/MarketingSuite/PurlContract.php
Purl services already have the store method from the base purl service, just makes it known.
https://vicimus.atlassian.net/browse/BUMP-6595
=> feat(shared): purl service has store

src/Interfaces/MarketingSuite/Campaign.php
Spoilter alert conquest is not email only
https://vicimus.atlassian.net/browse/BUMP-6665
=> feat(shared): campaign interface isEmailOnly

src/Interfaces/MarketingSuite/PurlEvent.php, src/Interfaces/MarketingSuite/PurlFiredEvent.php
Adds CTA method to the PurlFiredEvent
https://vicimus.atlassian.net/browse/BUMP-6674
=> feat(shared): retrieve cta id from purl event

src/Interfaces/MarketingSuite/ConquestDataSource.php, src/Interfaces/MarketingSuite/ConquestDataSourceCredentials.php
Implements a universal method for getting credentials from a data source using a provided store.
https://vicimus.atlassian.net/browse/BUMP-6787
=> dev(conquest): datasource provides credentials

src/Interfaces/Filtering/Stats.php
Taint a float bro.
https://vicimus.atlassian.net/browse/BUMP-6896
=> dev(shared): truth telling

src/Interfaces/Filtering/Filter.php
Filter has active property.
https://vicimus.atlassian.net/browse/BUMP-6504
=> dev(retention): filter interface

src/Interfaces/MarketingSuite/Campaign.php
Campaign HasMany prospects
https://vicimus.atlassian.net/browse/BUMP-5927
=> dev(shared): campaign has prospects

src/Database/Model.php
Ignore casting if told to.
https://vicimus.atlassian.net/browse/BUMP-6965
=> feat(shared): withoutCasts should ignore casts here too

src/Interfaces/Filtering/Campaign.php
While a conquest doesnt' actually have staggers, I need the relationship accessible from the interface
https://vicimus.atlassian.net/browse/BUMP-6376
=> feat(shared): campaign has staggers

src/Interfaces/MarketingSuite/Asset.php, src/Interfaces/MarketingSuite/AssetModel.php, src/Interfaces/MarketingSuite/Assets/Lockable.php, src/Interfaces/MarketingSuite/Assets/Validator.php, src/Interfaces/MarketingSuite/Campaign.php, src/Interfaces/MarketingSuite/Previewable.php, src/Interfaces/MarketingSuite/SimpleProperties.php
Interfaces changes to support asset builder version two on a retention campaign.
https://vicimus.atlassian.net/browse/BUMP-6415
=> dev(retention): interfaces for asset builder version two

src/Interfaces/MarketingSuite/Campaign.php
Campaign has postcard relationship
https://vicimus.atlassian.net/browse/BUMP-6408
=> dev(retention): campaign has postcard

src/Interfaces/MarketingSuite/Campaign.php
Asking those campaign questions.
https://vicimus.atlassian.net/browse/BUMP-7146
=> dev(shared): isPurlOnly

src/Interfaces/MarketingSuite/HasSource.php, src/Interfaces/MarketingSuite/SourceRecord.php
Source is now polymorphic and a 1:1 a opposed to 1:*. Adds the HasSource interface for conquest/intentory campaigns.
https://vicimus.atlassian.net/browse/BUMP-7210
=> dev(shared): has source interface, source has sourceable

src/Services/PoolDownloader.php, src/Services/PoolScanner.php
https://vicimus.atlassian.net/browse/GBX-5293?focusedCommentId=59373
=> Do not depend on a content-length to be successful

src/Classes/ConquestDataSourceInfo.php
This is required for connections refactoring.
https://vicimus.atlassian.net/browse/BUMP-7243
=> dev(shared): be able to set some attributes

src/Interfaces/MarketingSuite/Assets/PlaceholderData.php, src/Interfaces/MarketingSuite/Placeholderable.php
PLaceholderable interface to allow place holder data object to interact with an object other than a campaign.
https://vicimus.atlassian.net/browse/BUMP-7241
=> dev(shared): placeholderable

src/Interfaces/MarketingSuite/ConquestDataSource.php
Added a new method for ConquestDataSource
https://vicimus.atlassian.net/browse/BUMP-7291
=> fix(conquest): add method to conquestdatasource

src/Interfaces/MarketingSuite/Campaign.php, src/Interfaces/MarketingSuite/ConquestDataSource.php
This method should take a parameter. I can't explain why the related marketingsuite pr was passing.
https://vicimus.atlassian.net/browse/BUMP-7291
=> dev(shared): fix has valid credentials

src/Interfaces/MarketingSuite/AssetModel.php, src/Interfaces/MarketingSuite/Previewable.php
Fixed a typehint. Added an interface method for things to declare if they want AC to use fallback assets or not.
https://vicimus.atlassian.net/browse/BUMP-7250
=> dev(inventory-ads): preview support

src/Interfaces/MarketingSuite/ConquestDataSource.php, src/Interfaces/MarketingSuite/HasPurlDomain.php, src/Interfaces/MarketingSuite/HasSource.php, src/Interfaces/MarketingSuite/HasSourceAndPurlDomain.php, src/Interfaces/MarketingSuite/SourceRecord.php
Tweaks required to support inventory ads. Also removed a reference to a class inside marketing suite.
https://vicimus.atlassian.net/browse/BUMP-7241
=> dev(inventory-ads): interfaces for inventory ad changes

src/Interfaces/MarketingSuite/AssetModel.php, src/Interfaces/MarketingSuite/AssetRecord.php, src/Interfaces/MarketingSuite/HasSource.php
Changes required to make design editing work.
https://vicimus.atlassian.net/browse/BUMP-7249
=> dev(inventory-ads): interface changes

src/Interfaces/MarketingSuite/Asset.php, src/Interfaces/MarketingSuite/AssetModel.php, src/Interfaces/MarketingSuite/Assets/PreviewableAsset.php, src/Interfaces/MarketingSuite/Assets/Renderable.php
Assets and renderables need to be able to answer a few more questions.
https://vicimus.atlassian.net/browse/BUMP-7179
=> dev(shared): interface tweaks

src/Interfaces/MarketingSuite/AssetModel.php
These are required for an asset model to have.
https://vicimus.atlassian.net/browse/BUMP-7179
=> dev(shared): missed some methods

src/Interfaces/MarketingSuite/Assets/Creatable.php, src/Interfaces/MarketingSuite/Audience.php, src/Interfaces/MarketingSuite/ConquestDataSource.php
Adds the creatable interface used by assets/dynamic ads.
https://vicimus.atlassian.net/browse/BUMP-7180
=> dev(inventory-ads): creatable interface

src/Interfaces/MarketingSuite/ConquestDataSource.php
Datasources must be able to disable individual ads
https://vicimus.atlassian.net/browse/BUMP-7180
=> dev(shared): adds disable to data source interface

src/Interfaces/MarketingSuite/Assets/Creatable.php
Adds creativeName to the creatable interface used to retrieve a name for an ad placement
https://vicimus.atlassian.net/browse/BUMP-7180
=> dev(inventory-ads): creatable has creativeName

src/Interfaces/MarketingSuite/Assets/Creatable.php, src/Interfaces/MarketingSuite/ConquestDataSource.php, src/Interfaces/MarketingSuite/SourceRecord.php
Adds the custom audiences relationship to the source interface. 
Disable takes array.
https://vicimus.atlassian.net/browse/BUMP-7181
=> dev(shared): source has custom audiences 

.travis.yml, src/Services/FinanceCalculator.php, tests/Unit/Services/FinanceCalculatorTest.php
Reusable way to get payments.
https://vicimus.atlassian.net/browse/BUMP-7402
=> dev(shared): finance payment calculator

src/Interfaces/MarketingSuite/Placeholderable.php, src/Interfaces/MarketingSuite/RecordsLeads.php
Adds the records leads interface implemented by each campaign type,  used by the many purl services
https://vicimus.atlassian.net/browse/BUMP-7481
=> dev(shared): placeholderable knows version, adds records leads

src/Classes/RenderSpecs.php, tests/Unit/Classes/RenderSpecsTest.php
Allows telling the render service to make a postcard
https://vicimus.atlassian.net/browse/BUMP-7516
=> fix(retention): postcard toggle on render

src/Interfaces/MarketingSuite/Placeholderable.php
Adds form description/title methods to placeholderable.
https://vicimus.atlassian.net/browse/BUMP-7530
=> dev(shared): placeholderable provides form data

src/Interfaces/MarketingSuite/Assets/Renderable.php
Adds type() to the renderable interface
https://vicimus.atlassian.net/browse/BUMP-7444
=> dev(shared): renderable has type

src/Interfaces/MarketingSuite/AppointmentContract.php
Interface for appointment model.
https://vicimus.atlassian.net/browse/BUMP-7720
=> dev(shared): appointment contract

src/Interfaces/MarketingSuite/HasSource.php
Adds some methods to the has source interface for dealing with paused campaigns
https://vicimus.atlassian.net/browse/BUMP-7819
=> dev(shared): paused interface methods

src/Interfaces/ADF/ADFVehicle.php
Adds more interface methods to meet inventory requirements.
https://vicimus.atlassian.net/browse/BUMP-7811
=> dev(shared): vehicle interface methods

src/Database/Model.php, src/Interfaces/MarketingSuite/PurlContract.php, tests/Unit/Database/ModelTest.php
Purl method throws PurlException. SetAttribute respect noCasts setting.
https://vicimus.atlassian.net/browse/BUMP-8050
=> dev(shared): throws and model tweak

src/Interfaces/MarketingSuite/ConquestDataSource.php, src/Interfaces/MarketingSuite/CriteriaContract.php, src/Interfaces/MarketingSuite/ReportData.php
Tweaks to criteria contract for google ads changes.
https://vicimus.atlassian.net/browse/BUMP-8096
=> dev(shared): google ads changes

src/Exceptions/RemoteAdDoesNotExistException.php, src/Exceptions/RemoteCampaignDoesNotExistException.php, src/Interfaces/MarketingSuite/Assets/HasAssetDetails.php, src/Interfaces/MarketingSuite/HasSource.php
Adds an interface for retrieving a model which contains remote details on a placement. 
Adds a method to HasSource to retrieve this interface.
Adds some more specific data source exceptions
https://vicimus.atlassian.net/browse/BUMP-8202
=> dev(shared): asset details interfaces 

src/Interfaces/MarketingSuite/Previewable.php
Previewables also have to have assets (or a way to get them)
https://vicimus.atlassian.net/browse/BUMP-7754
=> dev(shared): more methods on previewable

src/Interfaces/MarketingSuite/SourceRecord.php
Adds budget type property hint to the source interface
https://vicimus.atlassian.net/browse/BUMP-8304
=> dev(shared): source has budget type

src/Exceptions/MergeException.php, src/Interfaces/PdfMerger.php
Makes the pdf merger an interface so there can be different implementations that can be swapped out at any time.
https://vicimus.atlassian.net/browse/BUMP-6278
=> dev(retention): pdf merger interface

src/Interfaces/MarketingSuite/ConquestDataSource.php
Adds the activate method to the source interface
https://vicimus.atlassian.net/browse/BUMP-6071
=> dev(shared): source has activate

src/Interfaces/MarketingSuite/ConquestDataSource.php
Adds the regenerate method to a conquest date source.
https://vicimus.atlassian.net/browse/BUMP-7364
=> dev(shared): data source regenerates

src/Services/LeaseCalculator.php, tests/Unit/Services/LeaseCalculatorTest.php
Make some of the protected methods public so I can use them outside of the class.
https://vicimus.atlassian.net/browse/BUMP-7512
=> dev(shared): calculator updates

src/Interfaces/MarketingSuite/ConquestDataSource.php
Adds a basic flag to the interface to indicate doing the bare minimum on processing.
https://vicimus.atlassian.net/browse/BUMP-8565
=> dev(shared): ads process takes a basic flag

src/Interfaces/Filtering/Campaign.php, src/Interfaces/OemService.php
Have they ever associated customers or not
https://vicimus.atlassian.net/browse/BUMP-6959
=> dev(shared): campaigns has associated

src/Interfaces/Filtering/Stats.php, src/Interfaces/MarketingSuite/Campaign.php
Adds somee fields to the postcard/campaign interfaces.
https://vicimus.atlassian.net/browse/BILL-199
=> dev(shared): postcard and campaign fields

src/Classes/API/CachesRequests.php, src/Database/Relations/HasManyFromAPI.php, src/Interfaces/Store.php, src/Testing/TestSqliteDatabase.php
Minor changes for better annotations and changes to make testing easier to manage.
https://vicimus.atlassian.net/browse/BUMP-9045
=> dev(shared): support for onyx auth

src/Interfaces/Billing/CostBreakdownContract.php, src/Interfaces/Filtering/Stats.php
Stats interface implements a breakdown method to retrieve the cost breakdown
https://vicimus.atlassian.net/browse/BUMP-9055
=> dev(rtention): stats has breakdown

src/Interfaces/Store.php
Adds setAttribute to the store interface
https://vicimus.atlassian.net/browse/BUMP-9092
https://vicimus.atlassian.net/browse/BUMP-9111
=> dev(shared): store interface has setAttribute

src/Interfaces/OnyxUser.php, src/Testing/Application.php, tests/Unit/Providers/QueueReporterProviderTest.php
You can ask a user if they have a group by id.
https://vicimus.atlassian.net/browse/BUMP-9173
=> dev(shared): changes required for sms inbox revamp

src/Interfaces/MarketingSuite/Identifiable.php
Adds shortUrl to identifiable.
https://vicimus.atlassian.net/browse/BSMS-36
=> dev(shared): add interface method shortUrl

src/Database/Model.php
ID
https://vicimus.atlassian.net/browse/BUMP-9248
=> dev(shared): did you know models have ids

src/Classes/Enums.php, tests/Unit/ParserTest.php
Add UK as a normalized country.
https://vicimus.atlassian.net/browse/BUMP-9297
=> dev(retention): adjust some customer stuff

src/Interfaces/OnyxUser.php
Just fixes a comment.
https://vicimus.atlassian.net/browse/BUMP-8895
=> dev(shared): fix comment

src/Interfaces/MarketingSuite/HasIdentifiers.php, src/Interfaces/MarketingSuite/HasPurlDomain.php, src/Interfaces/MarketingSuite/HasSource.php, src/Interfaces/MarketingSuite/PurlDomainContract.php, src/Interfaces/MarketingSuite/PurlEvent.php, src/Interfaces/MarketingSuite/PurlInteraction.php, src/Interfaces/MarketingSuite/PurlVouchers.php
Interface changes to allow display ads in retention
https://vicimus.atlassian.net/browse/BUMP-7615
=> dev(shared): purl interfaces

src/Interfaces/ScreenCapturer.php
Adds webp to contract to lower the file size.
Pass command to all versions
https://vicimus.atlassian.net/browse/BUMP-9338
=> dev(shared): adds webp method, command recording

src/Classes/Enums.php
Adds demo as a valid sale class value
https://vicimus.atlassian.net/browse/BUMP-9506
=> dev(shared): add demo to sale class

src/Interfaces/Filtering/Stats.php
Stats interface has BDC
https://vicimus.atlassian.net/browse/BUMP-9500
=> dev(shared): stats has bdc

src/Interfaces/Filtering/Campaign.php
Adds isBdcOnly to campaign interface
https://vicimus.atlassian.net/browse/BUMP-9490
=> dev(retention): campaign has bdc only

src/Interfaces/Filtering/Filter.php, src/Interfaces/Filtering/Gatherer.php
Changes to support medium scaling.
https://vicimus.atlassian.net/browse/BUMP-9265
=> dev(retention): changes for medium scaling

src/Testing/TestSqliteDatabase.php
We need to include the schema info in the hash to know if we need to run migrations or not.
https://vicimus.atlassian.net/browse/BUMP-9535
=> dev(shared): hash the schema

src/Database/Relations/HasManyFromAPI.php
It's hot garbage from when Marketingsuite was first built, and we didn't have a clear understanding of a lot of things.
https://vicimus.atlassian.net/browse/BUMP-9575
=> dev(shared): deprecated HasManyFromAPI class

bootstrap/helpers.php, src/Interfaces/Glovebox/Result.php, src/Interfaces/MarketingSuite/PurlEvents.php
https://vicimus.atlassian.net/browse/GBX-5699
=> move setting function above the laravel start early exit

src/Interfaces/Filtering/CustomerInformation.php, src/Interfaces/Filtering/Gatherer.php, src/Interfaces/MarketingSuite/Customer.php, src/Interfaces/MarketingSuite/PurlEvents.php, src/Testing/GuzzleRequests.php
The customer interface is a work in progress but needs to exist for the gatherer. Can be expanded on in the future as needed.
https://vicimus.atlassian.net/browse/BUMP-9265
=> dev(retention): changes to interfaces

src/Interfaces/Tel/CustomerListContract.php, src/Interfaces/Tel/CustomerListsContract.php
Adds class/service interfaces for Tel
https://vicimus.atlassian.net/browse/BUMP-9482
=> dev(retention): tel interfaces

src/Interfaces/Tel/CustomerListsContract.php
Contract changes
https://vicimus.atlassian.net/browse/TEL-318
=> dev(shared): customer list contract

src/Interfaces/Store.php
Just some property annotations. Bad practice and not how interfaces work but what ya gonna do.
https://vicimus.atlassian.net/browse/BUMP-9803
=> dev(shared): add to store interface

src/Interfaces/MarketingSuite/Assets/PlaceholderData.php
It's possible there is no one on the campaign or whatever.
https://vicimus.atlassian.net/browse/BUMP-8898
=> dev(shared): make identifiable nullable

src/Interfaces/ScreenCapturer.php
pdfBatch means that it will request for a batch and use the requests on the batch to create a bunch of pdfs.
https://vicimus.atlassian.net/browse/BUMP-10376
=> dev(shared): another screen capturer method

src/Traits/ConsoleOutputter.php, tests/Unit/Traits/ConsoleOutputterTest.php
Adds a catch around all the output methods to make sure vsrpintf doesnt fail
https://vicimus.atlassian.net/browse/BUMP-10606
=> dev(shared): console output safety

src/Interfaces/Glovebox/Promotions.php, src/Testing/TestSqliteDatabase.php
Make the interface more accurate. It's a shell of what is actually required.
https://vicimus.atlassian.net/browse/GBX-6132
=> dev(shared): changes for glovebox

src/Interfaces/MarketingSuite/Assets/Placeholders.php
Modifies params on isvalidplaceholder
https://vicimus.atlassian.net/browse/BUMP-10684
=> dev(shared): placeholders interface

src/Interfaces/Glovebox/Font.php
Adds some annotations to the Font class.
https://vicimus.atlassian.net/browse/GBX-6221
=> dev(shared): just some annotations

src/Database/Model.php
Baby us thought silencing exceptions was good, turns out, not silencing exceptions is good.
https://vicimus.atlassian.net/browse/BF2-54
=> dev(shared): better default

src/Classes/Enums.php, src/Classes/Parser.php
Allow F, C and L as payment types.
https://vicimus.atlassian.net/browse/BUMP-10903
=> feat(retention): support short form payment types

.github/workflows/standard.yml, src/Interfaces/Incentives/Incentive.php, src/Interfaces/Incentives/Institution.php
Adds chrome interfaces.
https://vicimus.atlassian.net/browse/GBX-6487
=> dev(shared): chrome interfaces

src/Interfaces/MarketingSuite/Asset.php, src/Interfaces/MarketingSuite/AssetRecord.php, src/Interfaces/MarketingSuite/Placeholderable.php, src/Interfaces/MarketingSuite/Previewable.php, src/Interfaces/PropertyRecord.php
These changes are required for Asset Builder changes.
https://vicimus.atlassian.net/browse/BUMP-11438
=> dev(shared): interfaces

src/Classes/Tools.php, tests/Unit/ToolsTest.php
Add More Excluded Filter Words During Data Upload
- voided
- family
- trust
@Quintile 
i've gone as far as `git push origin --delete BUMP-12043` and rebased a new branch off php74 (the dash -1). 
git status shows ONLY my 2 files, then i get here, 5 files changed... 
https://vicimus.atlassian.net/browse/BUMP-12043
=> fix(shared): add more excluded filter words

.github/workflows/standard.yml, src/Interfaces/Store.php, tests/Unit/ToolsTest.php
This method is required.
https://vicimus.atlassian.net/browse/BUMP-12222
=> dev(shared): required method in store implementations

src/Interfaces/Leads/Distribution.php
This is to support advanced lead and adf features.
https://vicimus.atlassian.net/browse/BUMP-12367
=> dev(shared): distribution interface

src/Interfaces/ADF/ADFLead.php
Adds a vehicle of interest related method to the interface.
https://vicimus.atlassian.net/browse/BUMP-12425
=> dev(retention): vehicle of interest

src/Interfaces/Leads/Distribution.php, src/Interfaces/MarketingSuite/Validatable.php
Adjust some distribution interface things.
https://vicimus.atlassian.net/browse/BUMP-12417
=> dev(shared): additional distribution methods

src/Interfaces/MarketingSuite/Assets/Creatable.php
Adds interface method to creatable.
https://vicimus.atlassian.net/browse/BUMP-12485
=> dev(shared): property without fallback on creatable

src/Services/MaturityCalculator.php, tests/Unit/Services/MaturityCalculatorTest.php
Use a shared service to calculate maturity so it can be used by both DMS and Customers/MS.
https://vicimus.atlassian.net/browse/BUMP-12746
=> feat(shared): maturity calculator

.github/workflows/standard.yml, resources/testing/lang/en/i18n.php, resources/testing/lang/en/i18n/fruit.php, resources/testing/lang/fr-CA/i18n.php, resources/testing/lang/fr-CA/i18n/fruit.php, src/Interfaces/ADF/ADFLead.php, src/Interfaces/Incentives/Incentive.php, src/Interfaces/Incentives/Institution.php, src/Interfaces/Leads/Distribution.php, src/Interfaces/Leads/HttpCallbackHandler.php, src/Interfaces/MarketingSuite/Assets/Creatable.php, src/Interfaces/MarketingSuite/SimpleProperties.php, src/Interfaces/MarketingSuite/Validatable.php, src/Interfaces/Store.php, src/Locale/Compiler.php, src/Locale/Translation.php, src/Services/MaturityCalculator.php, tests/Unit/Locale/CompilerTest.php, tests/Unit/Services/MaturityCalculatorTest.php
Whenever we develop new features for Marketingsuite, we develop these new features, interfaces, services, etc in the php74 branch. These changes and new developments are never merged into master, but if we eventually upgrade Marketingsuite to php8, we will be switching to use the master branch of support, and we need all these changes to be present or a bunch of work and fixes will just disappear and things will be broken.
=> dev(shared): merge php74 into master 

src/Interfaces/MarketingSuite/Campaign.php
A campaign must be both Eloquent and Placeholderable, it also has to provide a lead type id. We need to get away from using magical properties set by annotations that might not even be there and instead actually use interfaces the way they are meant to be used.
https://vicimus.atlassian.net/browse/BUMP-12988
=> dev(shared): better interface for campaign

src/Interfaces/Filtering/Campaign.php
Campaigns do not use batches.
https://vicimus.atlassian.net/browse/BUMP-13855
=> dev(shared): remove method
